<form action="<?= $this->url('publisher.activate') ?>" method="POST" name="publisherActivate-form" id="publisherActivate-form">
    Enter barcode of user to activate: <input type="text" name="barcode" value="73FBCF65D40D3C">
    <input type="submit" name="validate" class="btn btn-primary" value="Activate Z01 Publishers">
    <input type="hidden" name="libraryCode" value="Z01">
</form>

<br/>

<form action="<?= $this->url('publisher.deactivate') ?>" method="POST" name="publisherDeactivate-form" id="publisherDeactivate-form">
    Enter barcode of user to deactivate: <input type="text" name="barcode" value="73FBCF65D40D3C">
    <input type="submit" name="validate" class="btn btn-primary" value="Deactivate Z01 Publishers">
    <input type="hidden" name="libraryCode" value="Z01">
</form>
