<?php
$this->headLink()
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
    ->appendStylesheet('/default.css');

$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js')
    ->prependFile('/js/jquery.form.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js')
    ->prependFile('https://use.fontawesome.com/releases/v5.0.6/js/all.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <?=$this->headTitle('PURA User management')?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <link rel="icon" href="">
    <style>
        body { padding-top: 135px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
    </style>
</head>
<body class="app">

<header class="app-header">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
        <h3 style="color: white">PURA User Management</h3>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="<?= $this->url('purauser.barcodeentry') ?>" class="nav-link">
                            <i class="fa fa-check"></i> Activation
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="<?= $this->url('purauser.edit.emptyuser') ?>" class="nav-link">
                            <i class="fa fa-list-alt"></i> Control / Block
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="<?= $this->url('user.logout') ?>" class="nav-link">
                            <i class="fa fa-sign-out-alt"></i> Log out
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="<?= $this->url('publisher') ?>" class="nav-link">
                            <i class="fa fa-cog"></i> Admin-Only Area
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="app-content">
    <main class="container">
        <?=$this->content?>
    </main>
</div>

<?=$this->inlineScript()?>
<script language="JavaScript">
    function putContentInSidebar(response)
    {
        $('ul#search-results-list').html(response);
    }

    $( document ).ready(function() {
        if (document.location.pathname.indexOf('/purauser/edit') !== -1)
        {
            $('#search-form').ajaxForm(
                {
                    url: '/purauser/search',
                    type: 'post',
                    success: putContentInSidebar
                }
            );
        }
    });
</script>
</body>
</html>