<?php
/**
 * ${NAME}
 *
 * PHP version 5
 *
 * Copyright (C) project swissbib, University Library Basel, Switzerland
 * http://www.swissbib.org  / http://www.swissbib.ch / http://www.ub.unibas.ch
 *
 * Date: 09.02.18
 * Time: 14:20
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category Swissbib_VuFind2
 * @package  ${PACKAGE}
 * @author   Matthias Edel <matthias.edel@unibas.ch>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     http://www.swissbib.org
 */

echo $error;

$this->alephNrEntryForm->prepare();
?>

<table class="table"><tbody>
    <tr><td>Last Name:</td>     <td><?= $singlePuraUserRecord['lastname'] ?></td><tr>
    <tr><td>First Name:</td>    <td><?= $singlePuraUserRecord['firstname'] ?></td><tr>
    <tr><td>SWITCH edu-id:</td> <td><?= $singlePuraUserRecord['edu_id'] ?></td><tr>
    <tr><td>email:</td>         <td><?= $singlePuraUserRecord['email'] ?></td><tr>
</tbody></table>

<br/>
ID checked?<br/>
Address and account in Aleph verified?<br/>
<br/>
<form action="/purauser/alephnrentry/<?= $singlePuraUserRecord['barcode'] ?>" method="POST" name="alephNrEntry-form" id="alephNrEntry-form">

    <div class="form-group">
        <label>
            <span>Copy the user number from Aleph</span>
            <input type="text" name="alephNrEntry" value="">
        </label>
        <input type="submit" name="validate" value="Validate this user">
    </div>


</form>
