<?php

use PuraUserModel\Entity\PuraUserEntity;

/**
 * ${NAME}
 *
 * PHP version 5
 *
 * Copyright (C) project swissbib, University Library Basel, Switzerland
 * http://www.swissbib.org  / http://www.swissbib.ch / http://www.ub.unibas.ch
 *
 * Date: 09.02.18
 * Time: 14:20
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category Swissbib_VuFind2
 * @package  ${PACKAGE}
 * @author   Matthias Edel <matthias.edel@unibas.ch>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     http://www.swissbib.org
 */

echo '<p>' . $message . '</p>';
/**
 * @var PuraUserEntity $puraUserEntity
 */
?>

<h2>Add Aleph Number</h2>
<h4>User</h4>

<form class="form-horizontal">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">First Name:</label>
        <div class="mx-sm-6 mb-2">
            <input type="text" readonly class="form-control" value="<?= $puraUserEntity->getFirstname() ?>">
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Last Name:</label>
        <div class="mx-sm-6 mb-2">
            <input type="text" readonly class="form-control" value="<?= $puraUserEntity->getLastname()  ?>">
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email:</label>
        <div class="mx-sm-6 mb-2">
            <input type="text" readonly class="form-control" value="<?= $puraUserEntity->getEmail()  ?>">
        </div>
    </div>
</form>

<h4>Verification</h4>
<ul>
    <li>ID checked?</li>
    <li>Address and account in Aleph verified?</li>
</ul>
<form class="form-inline" action="/purauser/alephnrentry/<?= $puraUserEntity->getBarcode() ?>" method="POST" name="alephNrEntry-form" id="alephNrEntry-form">
    <div class="form-group mb-2">
        Copy the user number from Aleph :
    </div>
    <div class="form-group mx-sm-3 mb-2">
        <input class="form-control" type="text" placeholder="Aleph User Number" name="alephNrEntry" value="<?= $puraUserEntity->getLibrarySystemNumber() ?>">
    </div>
    <button type="submit" class="btn btn-primary mb-2">Validate this user</button>
</form>
