<?php

use PuraUserModel\Entity\PuraUserEntity;

/**
 * ${NAME}
 *
 * PHP version 5
 *
 * Copyright (C) project swissbib, University Library Basel, Switzerland
 * http://www.swissbib.org  / http://www.swissbib.ch / http://www.ub.unibas.ch
 *
 * Date: 09.02.18
 * Time: 14:20
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category Swissbib_VuFind2
 * @package  ${PACKAGE}
 * @author   Lionel Walter <lionel.walter@unibas.ch>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     http://www.swissbib.org
 */

/**
 * @var PuraUserEntity $puraUserEntity
 */
echo $error;
$this->editForm->prepare();
?>

<span>The user has been succesfully activated.</span>
<br/><br/>

<form action="" method="POST" name="edit-form" id="edit-form" class="form-horizontal">
    <table class="table"><tbody>
        <tr><td>Last Name:</td>       <td><?= $puraUserEntity->getLastname() ?></td><tr>
        <tr><td>First Name:</td>      <td><?= $puraUserEntity->getFirstname() ?></td><tr>
        <tr><td>SWITCH edu-id:</td>   <td><?= $puraUserEntity->getEduId() ?></td><tr>
        <tr><td>email:</td>           <td><?= $puraUserEntity->getEmail() ?></td><tr>
        <tr><td>activation date:</td> <td><?= $puraUserEntity->getAccessCreated() ?></td><tr>
        <tr><td>valid until:</td>     <td><?= $puraUserEntity->getDateExpiration() ?></td><tr>
        <tr><td>Aleph Number:</td>    <td><input type="text" name="edit-alephNr" value="<?= $puraUserEntity->getLibrarySystemNumber() ?>"></td></tr>
        <tr><td>Remark:</td>          <td><textarea name="edit-remark" rows="5" cols=""><?= $puraUserEntity->getRemarks() ?></textarea></td></tr>
        <tr><td><input type="submit" name="save" value="Save"></td><td></td></tr>
    </tbody></table>
    <input type="hidden" name="edit-userId" value="<?= $puraUserEntity->getUserId() ?>">
</form>

<form action="/publisher/deactivate" method="POST" name="edit-blockFromLib-form" id="edit-blockAllLibs-form">
    <input type="submit" name="save" value="Block this user from library">
</form>
<br/>

<form action="mailto:swissbib-ub@unibas.ch" method="POST" name="edit-blockAllLibs-form" id="edit-blockAllLibs-form">
    <input type="hidden" name="user" value="put user IDs here">
    <input type="submit" name="save" value="Block this user from all libraries">
</form>