<?php
//use App\Model\BaseModel;

/**
 * @var BaseModel[]    $puraUserList
 * @var String        $route
 */
?>
<?php foreach ($puraUserList as $puraUser): ?>
    <li>
        <a href="purauser/edit/<?=$puraUser['user_id']?>">
                <?= $this->escapeHtml($puraUser['user_id']) ?> - <?= $this->escapeHtml($puraUser['barcode']) ?> - <?= $this->escapeHtml($puraUser['edu_id']) ?>
        </a>
    </li>
<?php endforeach; ?>