<?php

use PuraUserModel\Entity\PuraUserEntity;

/**
 * @var PuraUserEntity[] $puraUserList
 * @var String           $route
 */
?>
<?php foreach ($puraUserList as $puraUser): ?>
    <li>
        <a href="/purauser/edit/<?=$puraUser->getBarcode()?>">
                <?= $this->escapeHtml($puraUser->getFirstname()) ?> <?= $this->escapeHtml($puraUser->getLastname()) ?>
        </a>
    </li>
<?php endforeach; ?>