<form id="search-form" class="form-inline">
    <div class="form-group mb-2 mr-sm-3">
        <input id="sidebarSearchbox" name="sidebarSearchbox" type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i></button>

</form>
<ul id="search-results-list" class="puraUserList">
    <?= $this->render('purauser::search'); ?>
</ul>




