<form id="search-form" class="searchForm form-search" action="/purauser/search" method="POST">
    <div class="input-append">
        <input id="sidebarSearchbox" name="sidebarSearchbox" type="text" class="search-query" placeholder="Search">
        <button type="submit" class="btn" disabled>search user</button>
    </div>
</form>
<ul id="search-results-list" class="puraUserList">
    <?= $this->render('purauser::search'); ?>
</ul>
